### ISSUE TITLE
Handle EmptyResultDataAccessException

### ISSUE THREAD

**Issue by mwarman** [leanstacks/skeleton-ws-spring-boot#12]
## Description

When attempting to delete an entity which has already been deleted, or simply does not exist, an EmptyResultDataAccessException is thrown.  Handle this exception gracefully to ensure the REST service client receives a consistent response.

### Sample
```
org.springframework.dao.EmptyResultDataAccessException: No class com.leanstacks.ws.model.Greeting entity with id 1 exists!
	at org.springframework.data.jpa.repository.support.SimpleJpaRepository.delete(SimpleJpaRepository.java:154) ~[spring-data-jpa-1.11.0.RELEASE.jar!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_102]
...
```

**Comment by mwarman** [comment]
Added `@ExceptionHandler` to `BaseController` for this type of Exception. Return HTTP 404 with empty response body.  Chose status code 404 over 410 because we do not know if the specific resource is temporarily or permanently unavailable. Also, from a security perspective, 404 is preferred because it obfuscates the disposition of the resource.

See [HTTP Status Codes](http://www.restapitutorial.com/httpstatuscodes.html) for additional reference.

**Comment by CLientLove** [comment]
The above  not enough to solve my problem, how do you do it？

**Comment by CLientLove** [comment]
SimpleJpaRepository source of the delete () method, add @Transactional,  delete the data that does not exist will throws Exception
